CREATE TABLE beers (
  `uuid` BINARY(16) DEFAULT (UUID_TO_BIN(UUID())),
  `version` INT DEFAULT NULL,
  `beer_name` VARCHAR(255) DEFAULT NULL,
  `beer_style` VARCHAR(255) DEFAULT NULL,
  `price` DOUBLE DEFAULT NULL,
  `created_date` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_date` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;